#配置选择配置文件
spring:
  profiles:
    active: dev

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false
    mode: HTML

#分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#mybatis classpath:mapper/**/*.xml
mybatis:
  type-aliases-package: com.peng.*.*.entity
  mapper-locations: classpath:mapper/*.xml


